export const SELECT_BOOK = 'books/SELECT_BOOK'
export const FETCH_BOOKS = 'books/FETCH_BOOKS'
export const FETCH_SUCCEEDED = 'books/FETCH_SUCCEEDED'

export const FETCH_SELECTED_BOOK = 'books/FETCH_SELECTED_BOOK'
export const FETCH_SELECTED_BOOK_SUCCEEDED = 'books/FETCH_SELECTED_BOOK_SUCCEEDED'
export const FETCH_SELECTED_BOOK_FAILED = 'books/FETCH_SELECTED_BOOK_FAILED'